### ISSUE TITLE
Welcome

### ISSUE THREAD

**Issue by stklik** [unige-pinfo-2018/PInfo2#1]
Dear SoftAware,

This is your repository. 
Please store all your developed code here, so we can verify your progress throughout the semester.
Feel free to use issues such as this one to communicate amongst each other, with me and with @mencattini .

Your VM Server will be `pinfo2` (IP: 129.194.69.129 ).
Your logins are not activated yet, I hope it will be done at the end of this week.

Next to the official assignment (work out a project proposal),
I ask you to do the following initial tasks:

* Each team member should comment on this post, to verify that you receive these notifications.
* Create a README file for this repo (add some text, list the team members, etc.)

Best of luck

PS: I received emails from two groups (SoftAware and  Théo Giovanna & co). If you should run into members of the third group, please tell them to contact me asap

**Comment by kaikoveritch** [comment]
Read and noted.

**Comment by BinkoP** [comment]
Read and noted

**Comment by LiquidSnake0** [comment]
Read and noted

**Comment by AAA97AAA** [comment]
Read and noted. Message transmitted to the third group.

**Comment by stklik** [comment]
> Message transmitted to the third group.

Thank you, @AAA97AAA

**Comment by Clasino** [comment]
Read and noted
