### ISSUE TITLE
VM logins

### ISSUE THREAD

**Issue by Clasino** [unige-pinfo-2018/PInfo2#2]
Nicolas tells me that he activated logins for the server. Can we have it and how do we connect?

**Comment by stklik** [comment]
Yes, I just received the same info from Nicolas.

Please look at #1 where the server IP is provided.
Try SSH to connect to the machine with your regular user + pw.
In your group I think you have been assigned as SysAdmin. 

This means that you should have also been added to the sudoers file.
Please verify your admin powers too.

**Comment by Clasino** [comment]
Everyone test it and it's ok. Thank you
